name: Quality Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    container:
      image: ramageek/image:php8.3-laravel-dev
      options: --workdir /var/www/html

    steps:
      - name: Clone Repository
        run: cd /var/www && rm -rf html && git clone https://github.com/ilham98/clean-code-calculator.git html && cd html && ls

      - name: Verify Clone
        run: |
          if [ -d "/var/www/html" ]; then
            echo "Repository cloned successfully"
            cd /var/www/html && ls -la
          else
            echo "Clone failed"
            exit 1
          fi

      - name: Show Status
        run: |
          pwd
          git status
        working-directory: /var/www/html

      - name: Setup Composer 
        run: |
          composer install --no-interaction --optimize-autoloader --quiet
        working-directory: /var/www/html

      - name: Run Quality Check
        run: |
          XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.xml
          cp sonar-project.properties.example sonar-project.properties
          sonar-scanner -Dsonar.login=${{ secrets.SONAR_LOGIN_TOKEN }} -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
        working-directory: /var/www/html